easy_admin:
    site_name: 'Administration'
    formats:
        date:     'd/m/Y'
        time:     'H\hi'
        datetime: 'd/m/Y \à H\hi'

    design:
        menu:
            - { label: admin.website_content }
            - { entity: 'Page', icon: 'file-alt', label: admin.pages.short }
            - { entity: 'Meta', icon: 'info', label: admin.metadata.short }

    entities:

        Page:
            class: App\Entity\Text
            label: admin.pages.full
            list:
                fields:
                    - { property: 'name', label: admin.name }
                    - { property: 'content', label: admin.content }
                dql_filter: "entity.type = 'html'"
                sort: 'name'
            form:
                fields:
                    - { type: 'group' }
                    - { property: 'name', label: admin.name, type_options: { disabled: true } }
                    - { property: 'content', label: admin.content }
                    # - { property: 'content', label: admin.content, type: 'fos_ckeditor', type_options: { config_name: 'config_with_uploadable_images', 'attr': {'size': 20}} }
            disabled_actions: ['new', 'delete']

        Meta:
            class: App\Entity\Text
            label: admin.metadata.full
            list:
                fields:
                    - { property: 'name', label: admin.name }
                    - { property: 'content', label: admin.content }
                dql_filter: "entity.type = 'meta'"
                sort: 'name'
            form:
                title: admin.metadata.edit
                fields:
                    - { property: 'name', label: admin.name, type_options: { disabled: true } }
                    - { property: 'content', label: admin.content }
            disabled_actions: ['new', 'delete']
