security:
    encoders:
        App\Entity\Admin:
            algorithm: auto

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: admin_provider
            custom_authenticators:
                - App\Security\AdminAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
            entry_point: App\Security\AdminAuthenticator

    access_control:
        - { path: ^/admin/login$, role: PUBLIC_ACCESS  }
        - { path: ^/admin, role: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

    enable_authenticator_manager: true